language: node_js
node_js:
    - "6"
before_script:
  - npm install -g gulp
before_deploy:
deploy:
  provider: npm
  api_key: $NPM_KEY
  email: "alain.metge@zenasoft.com"
  on:
    branch: master
  tag: next